server:
    port: 7770

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/nf?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 2001
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 200MB
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:vip/self/cliservice/mapper/xml/*.xml

myutil:
    captcha:
        effective: true
        border: 'no'
        color: black
        space: 5
    email:
        effective: true
        host-name: smtp.qq.com
        user-name: chenliangdengcom@qq.com
        password: orzcnpnmruvlcfhe
    oss:
        effective: true
        endpoint: oss-cn-hangzhou.aliyuncs.com
        key-id: LTAI5tHg78FPv67kyfbBEMEt
        key-secret: pI4N9NgydQWxrVCsDu5oK71KD2RxMg
        bucket-name: vip-self-001

debug: true